 
services:
  agent1:
    container_name: arangodb-agent1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod 
      - --server.endpoint=tcp://0.0.0.0:5101
      - --agency.my-address=tcp://agent1:5101
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent1
    ports:
      - "5101:5101"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  agent2:
    container_name: arangodb-agent2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:5102
      - --agency.my-address=tcp://agent2:5102
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent2
    ports:
      - "5102:5102"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  agent3:
    container_name: arangodb-agent3
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:5103
      - --agency.my-address=tcp://agent3:5103
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent3
    ports:
      - "5103:5103"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  dbserver1:
    container_name: arangodb-dbserver1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6101
      - --cluster.my-address=tcp://dbserver1:6101
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver1
    ports:
      - "6101:6101"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  dbserver2:
    container_name: arangodb-dbserver2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6102
      - --cluster.my-address=tcp://dbserver2:6102
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver2
    ports:
      - "6102:6102"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  dbserver3:
    container_name: arangodb-dbserver3
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6103
      - --cluster.my-address=tcp://dbserver3:6103
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver3
    ports:
      - "6103:6103"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  dbserver4:
    container_name: arangodb-dbserver4
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6104
      - --cluster.my-address=tcp://dbserver4:6104
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver4
    ports:
      - "6104:6104"
    deploy:
     resources:
      limits:
        memory: 1g
        cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  coordinator1:
    container_name: arangodb-coordinator1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:7101
      - --cluster.my-address=tcp://coordinator1:7101
      - --cluster.my-role=COORDINATOR
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/coordinator1
    ports:
      - "7101:7101"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network

  coordinator2:
    container_name: arangodb-coordinator2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:7102
      - --cluster.my-address=tcp://coordinator2:7102
      - --cluster.my-role=COORDINATOR
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/coordinator2
    ports:
      - "7102:7102"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "0.5"
    volumes:
      - /home/khabench/Desktop/test/data/Global:/data
    networks:
      - khab-network
networks:
  khab-network:
    driver: bridge