version: "3.9"

services:
  orientdb-node4:
    image: orientdb:latest
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node4
      - ORIENTDB_HOME=/orientdb
    ports:
      - "2427:2424"
      - "2483:2480"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-4
      resources:
        limits:
          memory: 4.0g
          cpus: "1.5"
    networks:
      - khab-network
  
  dbserver4:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6104
      - --cluster.my-address=tcp://dbserver4:6104
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver4
    ports:
      - "6104:6104"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-4
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  cratedb04:
    image: crate:latest
    ports:
      - "4204:4200"
    volumes:
      - ./data/cratedb/04:/data  # Montar el directorio data
    command:
      - crate
      - -Ccluster.name=crate-docker-cluster
      - -Cnode.name=cratedb04
      - -Cnode.data=true
      - -Cnetwork.host=_site_
      - -Cdiscovery.seed_hosts=cratedb01,cratedb02,cratedb03
      - -Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03
      - -Cgateway.expected_data_nodes=3
      - -Cgateway.recover_after_data_nodes=2
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-4
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

networks:
  khab-network:
    external: true
