version: "3.9"

services:
  orientdb-node1:
    image: orientdb:latest
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node1
      - ORIENTDB_HOME=/orientdb
    ports:
      - "2424:2424"
      - "2480:2480"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-1
      resources:
        limits:
          memory: 4.0g
          cpus: "1.5"
    networks:
      - khab-network

  agent1:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod 
      - --server.endpoint=tcp://0.0.0.0:5101
      - --agency.my-address=tcp://agent1:5101
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent1
    ports:
      - "5101:5101"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-1
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    networks:
      - khab-network

  dbserver1:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6101
      - --cluster.my-address=tcp://dbserver1:6101
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver1
    ports:
      - "6101:6101"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-1
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  coordinator1:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:7101
      - --cluster.my-address=tcp://coordinator1:7101
      - --cluster.my-role=COORDINATOR
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/coordinator1
    ports:
      - "7101:7101"
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-1
      resources:
        limits:
          memory: 2g
          cpus: "0.5"
    networks:
      - khab-network

  cratedb01:
    image: crate:latest
    ports:
      - "4201:4200"
    volumes:
      - ./data/cratedb/01:/data
    command: 
      - crate
      - -Ccluster.name=crate-docker-cluster
      - -Cnode.name=cratedb01
      - -Cnode.data=true
      - -Cnetwork.host=_site_
      - -Cdiscovery.seed_hosts=cratedb02,cratedb03
      - -Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03
      - -Cgateway.expected_data_nodes=3
      - -Cgateway.recover_after_data_nodes=2
    deploy:
      placement:
        constraints:
          - node.hostname == KHAB-1
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

networks:
  khab-network:
    external: true
