services:
  orientdb-node1:
    image: orientdb:latest
    container_name: orientdb-node1
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node1
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node1.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - /home/khabench/Desktop/test/data:/data  # Montar el directorio de datos
      - /home/khabench/Desktop/test/Dataset:/orientdb/load  # Montar Dataset en /orientdb/load
    ports:
      - "2424:2424"
      - "2480:2480"
    deploy:
      resources:
        limits:
          memory: 2.5g
          cpus: "1.5"
    networks:
      - khab-network

  orientdb-node2:
    image: orientdb:latest
    container_name: orientdb-node2
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node2
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node2.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - /home/khabench/Desktop/test/data:/data
      - /home/khabench/Desktop/test/Dataset:/orientdb/load  # Montar Dataset en /orientdb/load
    ports:
      - "2425:2424"
      - "2481:2480"
    deploy:
      resources:
        limits:
          memory: 2.5g
          cpus: "1.5"
    networks:
      - khab-network

  orientdb-node3:
    image: orientdb:latest
    container_name: orientdb-node3
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node3
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node3.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - /home/khabench/Desktop/test/data:/data
      - /home/khabench/Desktop/test/Dataset:/orientdb/load  # Montar Dataset en /orientdb/load
    ports:
      - "2426:2424"
      - "2482:2480"
    deploy:
      resources:
        limits:
          memory: 2.5g
          cpus: "1.5"
    networks:
      - khab-network

  orientdb-node4:
    image: orientdb:latest
    container_name: orientdb-node4
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node4
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node4.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - /home/khabench/Desktop/test/data:/data
      - /home/khabench/Desktop/test/Dataset:/orientdb/load  # Montar Dataset en /orientdb/load
    ports:
      - "2427:2424"
      - "2483:2480"
    deploy:
      resources:
        limits:
          memory: 2.5g
          cpus: "1.5"
    networks:
      - khab-network

networks:
  khab-network:
    driver: bridge

