CONNECT remote:localhost/KhaBench root rootpwd;

-- 📌 Crear Clusters para Fragmentación
CREATE CLUSTER customer_north_cluster;
CREATE CLUSTER post_long_cluster;
CREATE CLUSTER product_cheap_cluster;
CREATE CLUSTER customer_center_cluster;
CREATE CLUSTER post_medium_cluster;
CREATE CLUSTER order_pre_pandemic_cluster;
CREATE CLUSTER customer_south_cluster;
CREATE CLUSTER product_expensive_cluster;
CREATE CLUSTER order_post_pandemic_cluster;
CREATE CLUSTER customer_knows_person_cluster;
CREATE CLUSTER person_has_interest_tag_cluster;
CREATE CLUSTER post_has_creator_person_cluster;
CREATE CLUSTER post_has_tag_cluster;

-- 📌 Crear Clusters Globales (Nodo 4)
CREATE CLUSTER person_global_cluster;
CREATE CLUSTER customer_global_cluster;
CREATE CLUSTER product_global_cluster;
CREATE CLUSTER post_global_cluster;
CREATE CLUSTER order_global_cluster;
CREATE CLUSTER vendor_global_cluster;
CREATE CLUSTER tag_global_cluster;
CREATE CLUSTER feedback_global_cluster;
CREATE CLUSTER invoice_global_cluster;

-- 📌 **Crear Clases Globales con Propiedades, Restricciones y LINKS**
CREATE CLASS VENDOR EXTENDS V;
CREATE PROPERTY VENDOR.VENDOR_ID STRING;
ALTER PROPERTY VENDOR.VENDOR_ID MANDATORY TRUE;
ALTER PROPERTY VENDOR.VENDOR_ID NOTNULL TRUE;
CREATE PROPERTY VENDOR.COUNTRY STRING;
ALTER PROPERTY VENDOR.COUNTRY NOTNULL TRUE;
CREATE PROPERTY VENDOR.INDUSTRY STRING;
ALTER PROPERTY VENDOR.INDUSTRY NOTNULL TRUE;


CREATE CLASS PERSON EXTENDS V;
CREATE PROPERTY PERSON.PERSON_ID STRING;
ALTER PROPERTY PERSON.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON.FIRST_NAME STRING;
ALTER PROPERTY PERSON.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON.LAST_NAME STRING;
ALTER PROPERTY PERSON.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON.GENDER STRING;
ALTER PROPERTY PERSON.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON.BIRTHDAY DATE;
ALTER PROPERTY PERSON.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON.LOCATION_IP STRING;
ALTER PROPERTY PERSON.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON.BROWSER_USED STRING;
ALTER PROPERTY PERSON.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON.PLACE INTEGER;
ALTER PROPERTY PERSON.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_NORTH EXTENDS V;
CREATE PROPERTY PERSON_NORTH.PERSON_ID STRING;
ALTER PROPERTY PERSON_NORTH.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_NORTH.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.FIRST_NAME STRING;
ALTER PROPERTY PERSON_NORTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.LAST_NAME STRING;
ALTER PROPERTY PERSON_NORTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.GENDER STRING;
ALTER PROPERTY PERSON_NORTH.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.BIRTHDAY DATE;
ALTER PROPERTY PERSON_NORTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_NORTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.LOCATION_IP STRING;
ALTER PROPERTY PERSON_NORTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.BROWSER_USED STRING;
ALTER PROPERTY PERSON_NORTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.PLACE INTEGER;
ALTER PROPERTY PERSON_NORTH.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_SOUTH EXTENDS V;
CREATE PROPERTY PERSON_SOUTH.PERSON_ID STRING;
ALTER PROPERTY PERSON_SOUTH.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_SOUTH.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.FIRST_NAME STRING;
ALTER PROPERTY PERSON_SOUTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.LAST_NAME STRING;
ALTER PROPERTY PERSON_SOUTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.GENDER STRING;
ALTER PROPERTY PERSON_SOUTH.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.BIRTHDAY DATE;
ALTER PROPERTY PERSON_SOUTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_SOUTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.LOCATION_IP STRING;
ALTER PROPERTY PERSON_SOUTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.BROWSER_USED STRING;
ALTER PROPERTY PERSON_SOUTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.PLACE INTEGER;
ALTER PROPERTY PERSON_SOUTH.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_CENTER EXTENDS V;
CREATE PROPERTY PERSON_CENTER.PERSON_ID STRING;
ALTER PROPERTY PERSON_CENTER.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_CENTER.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.FIRST_NAME STRING;
ALTER PROPERTY PERSON_CENTER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.LAST_NAME STRING;
ALTER PROPERTY PERSON_CENTER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.GENDER STRING;
ALTER PROPERTY PERSON_CENTER.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.BIRTHDAY DATE;
ALTER PROPERTY PERSON_CENTER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_CENTER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.LOCATION_IP STRING;
ALTER PROPERTY PERSON_CENTER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.BROWSER_USED STRING;
ALTER PROPERTY PERSON_CENTER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.PLACE INTEGER;
ALTER PROPERTY PERSON_CENTER.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER EXTENDS V;
CREATE PROPERTY CUSTOMER.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.GENDER STRING;
ALTER PROPERTY CUSTOMER.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.PLACE INTEGER;
ALTER PROPERTY CUSTOMER.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_NORTH EXTENDS V;
CREATE PROPERTY CUSTOMER_NORTH.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_NORTH.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_NORTH.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_NORTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_NORTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.GENDER STRING;
ALTER PROPERTY CUSTOMER_NORTH.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_NORTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_NORTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_NORTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_NORTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_NORTH.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_CENTER EXTENDS V;
CREATE PROPERTY CUSTOMER_CENTER.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_CENTER.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_CENTER.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_CENTER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_CENTER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.GENDER STRING;
ALTER PROPERTY CUSTOMER_CENTER.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_CENTER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_CENTER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_CENTER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_CENTER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_CENTER.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_SOUTH EXTENDS V;
CREATE PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_SOUTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_SOUTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.GENDER STRING;
ALTER PROPERTY CUSTOMER_SOUTH.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_SOUTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_SOUTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_SOUTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_SOUTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_SOUTH.PLACE NOTNULL TRUE;


CREATE CLASS PRODUCT EXTENDS V;
CREATE PROPERTY PRODUCT.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT.TITLE STRING;
ALTER PROPERTY PRODUCT.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT.PRICE FLOAT;
ALTER PROPERTY PRODUCT.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT.PRICE MIN 0;
CREATE PROPERTY PRODUCT.IMG_URL STRING;
ALTER PROPERTY PRODUCT.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT.SKU STRING;
ALTER PROPERTY PRODUCT.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT.VENDOR_ID LINK VENDOR;  -- Relación a Vendor

CREATE CLASS PRODUCT_CHEAP EXTENDS V;
CREATE PROPERTY PRODUCT_CHEAP.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT_CHEAP.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT_CHEAP.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.TITLE STRING;
ALTER PROPERTY PRODUCT_CHEAP.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.PRICE FLOAT;
ALTER PROPERTY PRODUCT_CHEAP.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT_CHEAP.PRICE MIN 0;
CREATE PROPERTY PRODUCT_CHEAP.IMG_URL STRING;
ALTER PROPERTY PRODUCT_CHEAP.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.SKU STRING;
ALTER PROPERTY PRODUCT_CHEAP.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.VENDOR_ID LINK VENDOR;

CREATE CLASS PRODUCT_EXPENSIVE EXTENDS V;
CREATE PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.TITLE STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.PRICE FLOAT;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRICE MIN 0;
CREATE PROPERTY PRODUCT_EXPENSIVE.IMG_URL STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.SKU STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.VENDOR_ID LINK VENDOR;

CREATE CLASS POST EXTENDS V;
CREATE PROPERTY POST.POST_ID STRING;
ALTER PROPERTY POST.POST_ID MANDATORY TRUE;
ALTER PROPERTY POST.POST_ID NOTNULL TRUE;
CREATE PROPERTY POST.CREATE_DATE DATETIME;
CREATE PROPERTY POST.IMAGE_FILE STRING;
CREATE PROPERTY POST.LOCATION_IP STRING;
ALTER PROPERTY POST.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY POST.BROWSER_USED STRING;
ALTER PROPERTY POST.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY POST.CONTENT STRING;
CREATE PROPERTY POST.LENGTH INTEGER;
ALTER PROPERTY POST.LENGTH MIN 0;

CREATE CLASS POST_SHORT EXTENDS V;
CREATE PROPERTY POST_SHORT.POST_ID STRING;
ALTER PROPERTY POST_SHORT.POST_ID MANDATORY TRUE;
ALTER PROPERTY POST_SHORT.POST_ID NOTNULL TRUE;
CREATE PROPERTY POST_SHORT.CREATE_DATE DATETIME;
CREATE PROPERTY POST_SHORT.IMAGE_FILE STRING;
CREATE PROPERTY POST_SHORT.LOCATION_IP STRING;
ALTER PROPERTY POST_SHORT.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY POST_SHORT.BROWSER_USED STRING;
ALTER PROPERTY POST_SHORT.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY POST_SHORT.LANGUAGE STRING;
CREATE PROPERTY POST_SHORT.CONTENT STRING;
CREATE PROPERTY POST_SHORT.LENGTH INTEGER;

CREATE CLASS POST_MEDIUM EXTENDS V;
CREATE PROPERTY POST_MEDIUM.POST_ID STRING;
ALTER PROPERTY POST_MEDIUM.POST_ID MANDATORY TRUE;
ALTER PROPERTY POST_MEDIUM.POST_ID NOTNULL TRUE;
CREATE PROPERTY POST_MEDIUM.CREATE_DATE DATETIME;
CREATE PROPERTY POST_MEDIUM.IMAGE_FILE STRING;
CREATE PROPERTY POST_MEDIUM.LOCATION_IP STRING;
ALTER PROPERTY POST_MEDIUM.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY POST_MEDIUM.LANGUAGE STRING;
CREATE PROPERTY POST_MEDIUM.BROWSER_USED STRING;
ALTER PROPERTY POST_MEDIUM.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY POST_MEDIUM.CONTENT STRING;
CREATE PROPERTY POST_MEDIUM.LENGTH INTEGER;

CREATE CLASS POST_LONG EXTENDS V;
CREATE PROPERTY POST_LONG.POST_ID STRING;
ALTER PROPERTY POST_LONG.POST_ID MANDATORY TRUE;
ALTER PROPERTY POST_LONG.POST_ID NOTNULL TRUE;
CREATE PROPERTY POST_LONG.CREATE_DATE DATETIME;
CREATE PROPERTY POST_LONG.IMAGE_FILE STRING;
CREATE PROPERTY POST_LONG.LOCATION_IP STRING;
ALTER PROPERTY POST_LONG.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY POST_LONG.BROWSER_USED STRING;
ALTER PROPERTY POST_LONG.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY POST_LONG.LANGUAGE STRING;
CREATE PROPERTY POST_LONG.CONTENT STRING;
CREATE PROPERTY POST_LONG.LENGTH INTEGER;


-- 📌 **Crear Relaciones usando LINK y LINKLIST**
CREATE CLASS ORDER EXTENDS V;
CREATE PROPERTY ORDER.ORDER_ID STRING;
ALTER PROPERTY ORDER.ORDER_ID MANDATORY TRUE;
ALTER PROPERTY ORDER.ORDER_ID NOTNULL TRUE;
CREATE PROPERTY ORDER.CUSTOMER_ID LINK CUSTOMER;  -- FK a Customer
CREATE PROPERTY ORDER.ORDER_DATE STRING;
ALTER PROPERTY ORDER.ORDER_DATE NOTNULL TRUE;
CREATE PROPERTY ORDER.TOTAL_PRICE FLOAT;
ALTER PROPERTY ORDER.TOTAL_PRICE MIN 0;
ALTER PROPERTY ORDER.TOTAL_PRICE NOTNULL TRUE;
CREATE PROPERTY ORDER.PRODUCT LINKLIST PRODUCT;  -- Relación N:M con productos

-- 📌 **Crear Clases Fragmentadas**
CREATE CLASS ORDER_PRE_PANDEMIC EXTENDS V;
CREATE PROPERTY  ORDER_PRE_PANDEMIC.ORDER_ID STRING;
ALTER PROPERTY  ORDER_PRE_PANDEMIC.ORDER_ID MANDATORY TRUE;
ALTER PROPERTY  ORDER_PRE_PANDEMIC.ORDER_ID NOTNULL TRUE;
CREATE PROPERTY  ORDER_PRE_PANDEMIC.CUSTOMER_ID LINK CUSTOMER;  -- FK a Customer
CREATE PROPERTY  ORDER_PRE_PANDEMIC.ORDER_DATE STRING;
ALTER PROPERTY  ORDER_PRE_PANDEMIC.ORDER_DATE NOTNULL TRUE;
CREATE PROPERTY  ORDER_PRE_PANDEMIC.TOTAL_PRICE FLOAT;
ALTER PROPERTY  ORDER_PRE_PANDEMIC.TOTAL_PRICE MIN 0;
ALTER PROPERTY  ORDER_PRE_PANDEMIC.TOTAL_PRICE NOTNULL TRUE;
CREATE PROPERTY  ORDER_PRE_PANDEMIC.PRODUCT LINKLIST PRODUCT; 

CREATE CLASS ORDER_POST_PANDEMIC EXTENDS V;
CREATE PROPERTY ORDER_POST_PANDEMIC.ORDER_ID STRING;
ALTER PROPERTY ORDER_POST_PANDEMIC.ORDER_ID MANDATORY TRUE;
ALTER PROPERTY ORDER_POST_PANDEMIC.ORDER_ID NOTNULL TRUE;
CREATE PROPERTY ORDER_POST_PANDEMIC.CUSTOMER_ID LINK CUSTOMER;  -- FK a Customer
CREATE PROPERTY ORDER_POST_PANDEMIC.ORDER_DATE STRING;
ALTER PROPERTY ORDER_POST_PANDEMIC.ORDER_DATE NOTNULL TRUE;
CREATE PROPERTY ORDER_POST_PANDEMIC.TOTAL_PRICE FLOAT;
ALTER PROPERTY ORDER_POST_PANDEMIC.TOTAL_PRICE MIN 0;
ALTER PROPERTY ORDER_POST_PANDEMIC.TOTAL_PRICE NOTNULL TRUE;
CREATE PROPERTY ORDER_POST_PANDEMIC.PRODUCT LINKLIST PRODUCT;

CREATE CLASS FEEDBACK EXTENDS V;
CREATE PROPERTY FEEDBACK.PRODUCT_ID LINK PRODUCT;  -- Relación a producto
CREATE PROPERTY FEEDBACK.CUSTOMER_ID LINK CUSTOMER;  -- Relación a cliente
CREATE PROPERTY FEEDBACK.RATE FLOAT;
ALTER PROPERTY FEEDBACK.RATE NOTNULL TRUE;
CREATE PROPERTY FEEDBACK.REVIEW STRING;
ALTER PROPERTY FEEDBACK.REVIEW NOTNULL TRUE;

CREATE CLASS TAG EXTENDS V;
CREATE PROPERTY TAG.TAG_ID STRING;
ALTER PROPERTY TAG.TAG_ID MANDATORY TRUE;
ALTER PROPERTY TAG.TAG_ID NOTNULL TRUE;
CREATE PROPERTY TAG.TITLE STRING;
ALTER PROPERTY TAG.TITLE NOTNULL TRUE;


CREATE CLASS INVOICE EXTENDS V;
CREATE PROPERTY INVOICE.ORDER_ID STRING;
ALTER PROPERTY INVOICE.ORDER_ID MANDATORY TRUE;
ALTER PROPERTY INVOICE.ORDER_ID NOTNULL TRUE;
CREATE PROPERTY INVOICE.CUSTOMER_ID LINK Customer;  -- FK a Customer
CREATE PROPERTY INVOICE.ORDER_DATE STRING;
ALTER PROPERTY INVOICE.ORDER_DATE NOTNULL TRUE;
CREATE PROPERTY INVOICE.TOTAL_PRICE FLOAT;
ALTER PROPERTY INVOICE.TOTAL_PRICE MIN 0;
ALTER PROPERTY INVOICE.TOTAL_PRICE NOTNULL TRUE;
CREATE PROPERTY INVOICE.PRODUCT LINKLIST PRODUCT;




-- 📌 **Relaciones (Edges)**
CREATE CLASS CUSTOMER_KNOWS_PERSON EXTENDS E;
CREATE CLASS PERSON_HAS_INTEREST_TAG EXTENDS E;
CREATE CLASS POST_HAS_CREATOR_PERSON EXTENDS E;
CREATE CLASS POST_HAS_TAG EXTENDS E;

--- 📌 **Asignar Clusters Globales a Clases Globales**
ALTER CLASS Person ADDCLUSTER person_global_cluster;
ALTER CLASS Customer ADDCLUSTER customer_global_cluster;
ALTER CLASS Product ADDCLUSTER product_global_cluster;
ALTER CLASS Post ADDCLUSTER post_global_cluster;
ALTER CLASS Order ADDCLUSTER order_global_cluster;
ALTER CLASS Vendor ADDCLUSTER vendor_global_cluster;
ALTER CLASS Tag ADDCLUSTER tag_global_cluster;
ALTER CLASS Feedback ADDCLUSTER feedback_global_cluster;
ALTER CLASS Invoice ADDCLUSTER invoice_global_cluster;

-- 📌 **Asignar Clusters a Clases Fragmentadas**
ALTER CLASS Customer_North ADDCLUSTER customer_north_cluster;
ALTER CLASS Post_Long ADDCLUSTER post_long_cluster;
ALTER CLASS Product_Cheap ADDCLUSTER product_cheap_cluster;
ALTER CLASS Customer_Center ADDCLUSTER customer_center_cluster;
ALTER CLASS Post_Medium ADDCLUSTER post_medium_cluster;
ALTER CLASS Order_Pre_Pandemic ADDCLUSTER order_pre_pandemic_cluster;
ALTER CLASS Customer_South ADDCLUSTER customer_south_cluster;
ALTER CLASS Product_Expensive ADDCLUSTER product_expensive_cluster;
ALTER CLASS Order_Post_Pandemic ADDCLUSTER order_post_pandemic_cluster;

-- 📌 **Asignar Clusters a Relaciones (Edges)**
ALTER CLASS CUSTOMER_KNOWS_PERSON ADDCLUSTER customer_knows_person_cluster;
ALTER CLASS PERSON_HAS_INTEREST_TAG ADDCLUSTER person_has_interest_tag_cluster;
ALTER CLASS POST_HAS_CREATOR_PERSON ADDCLUSTER post_has_creator_person_cluster;
ALTER CLASS POST_HAS_TAG ADDCLUSTER post_has_tag_cluster;

-- 📌 **Crear Relaciones**
CREATE EDGE CUSTOMER_KNOWS_PERSON FROM (SELECT FROM Customer) TO (SELECT FROM Person);
CREATE EDGE PERSON_HAS_INTEREST_TAG FROM (SELECT FROM Person) TO (SELECT FROM Tag);
CREATE EDGE POST_HAS_CREATOR_PERSON FROM (SELECT FROM Post) TO (SELECT FROM Person);
CREATE EDGE POST_HAS_TAG FROM (SELECT FROM Post) TO (SELECT FROM Tag);

-- 📌 **Confirmación de Clases y Propiedades**
SELECT FROM (SELECT expand(classes) FROM metadata:schema);