services:
  cratedb01:
    container_name: cratedb-node1
    image: crate:latest
    ports:
      - "4201:4200"
    volumes:
      - ./data/cratedb/01:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

  cratedb02:
    container_name: cratedb-node2
    image: crate:latest
    ports:
      - "4202:4200"
    volumes:
      - ./data/cratedb/02:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

  cratedb03:
    container_name: cratedb-node3
    image: crate:latest
    ports:
      - "4203:4200"
    volumes:
      - ./data/cratedb/03:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network
networks:
  khab-network:
    driver: bridge
